spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: misso
    password: misso
  #    publisher-returns: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: 1111111111@1111111.ru
    password: 1111111111111111111111
    smtps:
      auth: true
logging:
  level:
    root: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%level] %msg%n"
  file:
    name: log.txt